import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Compilot",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <head>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            (() => {
                                const theme =
                                    localStorage.getItem("compilot-theme") || "light";

                                document.documentElement.dataset.theme = theme;
                            })();
                        `,
                    }}
                />
            </head>

            <body className="min-h-full flex flex-col">
                {children}
            </body>
        </html>
    );
}